name: Continuous Integration

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        steps: ["lint", "build-frontend", "build-backend", "docker-build"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Frontend Dependencies
        working-directory: affirmations-frontend
        run: pnpm install

      - name: Check Linter - TypeScript
        run: pnpm lint

      - name: Format Code - TypeScript
        working-directory: affirmations-frontend
        run: pnpm format-check

      - name: Build Frontend
        working-directory: affirmations-frontend
        run: pnpm build

      - name: Install Backend Dependencies
        working-directory: affirmations-backend
        run: pip install -r requirements.txt
