name: CleverHug Backend Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
on:
  push:
    branches:
      - master
    paths:
      - "CleverHug-Backend/**"
  workflow_dispatch:
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        working-directory: ./CleverHug-Backend
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        working-directory: ./CleverHug-Backend
        run: vercel build --prod --force --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        working-directory: ./CleverHug-Backend
        run: vercel deploy --prebuilt --prod --force --token=${{ secrets.VERCEL_TOKEN }}
